/* Generated By:JJTree: Do not edit this line. ASTRECharList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTRECharList extends JJTreeNode{
  public ASTRECharList(int id) {
    super(id);
  }

  public ASTRECharList(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0cad8a2297a5be7ed37bf6724c3dba91 (do not edit this line) */
