/* Generated By:JJTree: Do not edit this line. ASTRESequence.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTRESequence extends JJTreeNode{
  public ASTRESequence(int id) {
    super(id);
  }

  public ASTRESequence(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=13ea8d5a4d49449e8c42b5ac4be32173 (do not edit this line) */
