options {
    BUILD_FUZZER=true;
}

PARSER_BEGIN(SimpleFuzzer)
package org.javacc.test.simpleFuzzer;

import java.util.List;
import java.util.ArrayList;

public class SimpleFuzzer {
}

PARSER_END(SimpleFuzzer)

SKIP :
{
  " "
| "\t"
| "\n"
| "\r"
}

TOKEN :
{
  < Id: ["A"-"C"] "HELLO" "WORLD" ( ["0"-"9"] )* >  { System.out.println("token: id"); }
}

/** Top level production. */
List<String> Ids() :
{
    Token id;
    List<String> ids = new ArrayList<String>();
}
{
  ( id = <Id> { ids.add(id.image); } )+ <EOF> { return ids; }
}
