options {
    BUILD_FUZZER=true;
}

PARSER_BEGIN(SimpleFuzzer)
package org.javacc.test.simpleFuzzer;

import java.util.List;
import java.util.ArrayList;

public class SimpleFuzzer {
}

PARSER_END(SimpleFuzzer)

SKIP :
{
  " "
| "\t"
| "\n"
| "\r"
}

TOKEN :
{
  < Id: ["A"-"Z"] (["0"-"9", "a"-"z"])+ >
  | < Select: "SELECT" >
  | < From: "FROM" >
  | < Where: "WHERE" >
}

/** Top level production. */
List<String> Select() :
{
    Token t;
    Token v;
    String c;
    List<String> res = new ArrayList<String>();
}
{
  <Select> { res.add("select"); } t=<Id> { res.add("column=" + t.image); } ("," t=<Id> { res.add("column=" + t.image); })*
    <From> { res.add("from"); } t=<Id> { res.add("table=" + t.image); }
    [ <Where> { res.add("where"); } c=Condition() { res.add(c); } ]
    <EOF> { return res; }
}

String Condition() :
{
    Token t;
    String u;
    String v;
}
{
  t=<Id> { u = t.image; } "=" t=<Id>
  {
    v = t.image;
    return "condition=[" + u + "==" + v + "]";
  }
}
