/* Generated By:JJTree: Do not edit this line. ASTRE.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTRE extends JJTreeNode{
  public ASTRE(int id) {
    super(id);
  }

  public ASTRE(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6c7bc855130c7cb17cc5d4f4ccab39f4 (do not edit this line) */
