/* Generated By:JJTree: Do not edit this line. ASTBNFZeroOrOne.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFZeroOrOne extends JJTreeNode{
  public ASTBNFZeroOrOne(int id) {
    super(id);
  }

  public ASTBNFZeroOrOne(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3c8f996dd6a2b8e15673404c8d50952e (do not edit this line) */
