language: java
jdk: openjdk8
install:
  - skip
matrix:
  include:
    - name: Maven
      script:
        - mvn test -B -Dgpg.skip=true
    - name: Gradle
      script:
        - ./gradlew --no-daemon build javadoc
