/* Generated By:JJTree: Do not edit this line. ASTRENamed.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTRENamed extends JJTreeNode{
  public ASTRENamed(int id) {
    super(id);
  }

  public ASTRENamed(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=83df1f5a13116381eb6ff03428c608ca (do not edit this line) */
