
options { OUTPUT_DIRECTORY="out-dir"; }

PARSER_BEGIN(Parser)

public class Parser {

  public static void main(String args[]) throws Exception {
    Parser t = new Parser(System.in);
    t.CompilationUnit();
    System.out.println("Parser ran sucessfully");
  }

}

PARSER_END(Parser)

TOKEN :
{
  < FOO: "FOO">
| < BAR: "BAR">
| < DUMMY: "DUMMY">
}

void CompilationUnit() : {}
{
	LOOKAHEAD(2)
	( <FOO> | {}) <BAR> <DUMMY>
	|
	<BAR> <BAR>
}
