#!/bin/sh -f

# Copyright © 2002 Sun Microsystems, Inc., 4150 Network Circle, Santa Clara,
# California 95054, U.S.A. All rights reserved.  Sun Microsystems, Inc. has
# intellectual property rights relating to technology embodied in the product
# that is described in this document. In particular, and without limitation,
# these intellectual property rights may include one or more of the U.S.
# patents listed at http://www.sun.com/patents and one or more additional
# patents or pending patent applications in the U.S. and in other countries.
# U.S. Government Rights - Commercial software. Government users are subject
# to the Sun Microsystems, Inc. standard license agreement and applicable
# provisions of the FAR and its supplements.  Use is subject to license terms.
# Sun,  Sun Microsystems,  the Sun logo and  Java are trademarks or registered
# trademarks of Sun Microsystems, Inc. in the U.S. and other countries.  This
# product is covered and controlled by U.S. Export Control laws and may be
# subject to the export or import laws in other countries.  Nuclear, missile,
# chemical biological weapons or nuclear maritime end uses or end users, whether
# direct or indirect, are strictly prohibited.  Export or reexport to countries
# subject to U.S. embargo or to entities identified on U.S. export exclusion
# lists, including, but not limited to, the denied persons and specially
# designated nationals lists is strictly prohibited.

install_name="javacc-$1"
export install_name
/bin/rm -rf dist
/bin/rm -f ${install_name}.tar.gz
/bin/rm -f ${install_name}.zip
mkdir -p dist/${install_name}
cp -rf bin dist/${install_name}/bin
chmod a+x dist/${install_name}/bin/javacc
chmod a+x dist/${install_name}/bin/jjdoc
chmod a+x dist/${install_name}/bin/jjtree
cp -rf www/doc dist/${install_name}/doc
cp -rf examples dist/${install_name}/examples

find dist -name CVS -exec /bin/rm -rf {} \; 1> /dev/null 2>&1 
cd dist
tar cpf ../${install_name}.tar .
gzip ../${install_name}.tar
zip -qr ../${install_name}.zip .
/bin/rm -rf dist
