/* Generated By:JJTree: Do not edit this line. ASTBNFNodeScope.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTBNFNodeScope extends JJTreeNode {
  public ASTBNFNodeScope(int id) {
    super(id);
  }

  public ASTBNFNodeScope(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visitASTBNFNodeScope(this, data);
  }
}
/* JavaCC - OriginalChecksum=83015f6d290a04827f71692f1aff554f (do not edit this line) */
