/* Generated By:JJTree: Do not edit this line. ASTBNF.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTBNF extends JJTreeNode {
  public ASTBNF(int id) {
    super(id);
  }

  public ASTBNF(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visitASTBNF(this, data);
  }
}
/* JavaCC - OriginalChecksum=22223f013a5fc382de41924ecc610d45 (do not edit this line) */
