/* Generated By:JJTree: Do not edit this line. ASTBNFDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTBNFDeclaration extends JJTreeNode {
  public ASTBNFDeclaration(int id) {
    super(id);
  }

  public ASTBNFDeclaration(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visitASTBNFDeclaration(this, data);
  }
}
/* JavaCC - OriginalChecksum=de68a68a42c9f6a37d4338de1e21d1c2 (do not edit this line) */
