/* Generated By:JJTree: Do not edit this line. ASTExpansionNodeScope.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTExpansionNodeScope extends JJTreeNode {
  public ASTExpansionNodeScope(int id) {
    super(id);
  }

  public ASTExpansionNodeScope(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visitASTExpansionNodeScope(this, data);
  }
}
/* JavaCC - OriginalChecksum=bea0524eca77d716f9537fde28452ace (do not edit this line) */
