/* Generated By:JJTree: Do not edit this line. ASTJavacodeBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTJavacodeBody extends JJTreeNode {
  public ASTJavacodeBody(int id) {
    super(id);
  }

  public ASTJavacodeBody(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visitASTJavacodeBody(this, data);
  }
}
/* JavaCC - OriginalChecksum=535d78fcc18d839ae72e07c068653c71 (do not edit this line) */
