/* Generated By:JJTree: Do not edit this line. ASTNodeDescriptorExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTNodeDescriptorExpression extends JJTreeNode {
  public ASTNodeDescriptorExpression(int id) {
    super(id);
  }

  public ASTNodeDescriptorExpression(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visitASTNodeDescriptorExpression(this, data);
  }
}
/* JavaCC - OriginalChecksum=0bf8969b1d221acaaf9c441c54b0e8ca (do not edit this line) */
