/* Generated By:JJTree: Do not edit this line. ASTNodeDescriptor.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTNodeDescriptor extends JJTreeNode {
  public ASTNodeDescriptor(int id) {
    super(id);
  }

  public ASTNodeDescriptor(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visitASTNodeDescriptor(this, data);
  }
}
/* JavaCC - OriginalChecksum=7e57ffe8f4821f5f28129f8398bc0df5 (do not edit this line) */
