/* Generated By:JJTree: Do not edit this line. ASTOptionBinding.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTOptionBinding extends JJTreeNode {
  public ASTOptionBinding(int id) {
    super(id);
  }

  public ASTOptionBinding(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visitASTOptionBinding(this, data);
  }
}
/* JavaCC - OriginalChecksum=b3860c38ce20131b202dbfbc0f3869d7 (do not edit this line) */
