/* Generated By:JJTree: Do not edit this line. ASTProductions.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTProductions extends JJTreeNode{
  public ASTProductions(int id) {
    super(id);
  }

  public ASTProductions(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9cb8dddc4986df9ebf59cb212c5f3692 (do not edit this line) */
