/* Generated By:JJTree: Do not edit this line. ASTREChoice.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREChoice extends JJTreeNode{
  public ASTREChoice(int id) {
    super(id);
  }

  public ASTREChoice(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7ff898fef37b107f5180f77b6c13316c (do not edit this line) */
