/* Generated By:JJTree&JavaCC: Do not edit this line. JJTreeParserConstants.java */
package org.javacc.jjtree;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JJTreeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int _LOOKAHEAD = 1;
  /** RegularExpression Id. */
  int _IGNORE_CASE = 2;
  /** RegularExpression Id. */
  int _PARSER_BEGIN = 3;
  /** RegularExpression Id. */
  int _PARSER_END = 4;
  /** RegularExpression Id. */
  int _JAVACODE = 5;
  /** RegularExpression Id. */
  int _TOKEN = 6;
  /** RegularExpression Id. */
  int _SPECIAL_TOKEN = 7;
  /** RegularExpression Id. */
  int _MORE = 8;
  /** RegularExpression Id. */
  int _SKIP = 9;
  /** RegularExpression Id. */
  int _TOKEN_MGR_DECLS = 10;
  /** RegularExpression Id. */
  int _EOF = 11;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 20;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 21;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 22;
  /** RegularExpression Id. */
  int ABSTRACT = 24;
  /** RegularExpression Id. */
  int BOOLEAN = 25;
  /** RegularExpression Id. */
  int BREAK = 26;
  /** RegularExpression Id. */
  int BYTE = 27;
  /** RegularExpression Id. */
  int CASE = 28;
  /** RegularExpression Id. */
  int CATCH = 29;
  /** RegularExpression Id. */
  int CHAR = 30;
  /** RegularExpression Id. */
  int CLASS = 31;
  /** RegularExpression Id. */
  int CONST = 32;
  /** RegularExpression Id. */
  int CONTINUE = 33;
  /** RegularExpression Id. */
  int _DEFAULT = 34;
  /** RegularExpression Id. */
  int DO = 35;
  /** RegularExpression Id. */
  int DOUBLE = 36;
  /** RegularExpression Id. */
  int ELSE = 37;
  /** RegularExpression Id. */
  int EXTENDS = 38;
  /** RegularExpression Id. */
  int FALSE = 39;
  /** RegularExpression Id. */
  int FINAL = 40;
  /** RegularExpression Id. */
  int FINALLY = 41;
  /** RegularExpression Id. */
  int FLOAT = 42;
  /** RegularExpression Id. */
  int FOR = 43;
  /** RegularExpression Id. */
  int GOTO = 44;
  /** RegularExpression Id. */
  int IF = 45;
  /** RegularExpression Id. */
  int IMPLEMENTS = 46;
  /** RegularExpression Id. */
  int IMPORT = 47;
  /** RegularExpression Id. */
  int INSTANCEOF = 48;
  /** RegularExpression Id. */
  int INT = 49;
  /** RegularExpression Id. */
  int INTERFACE = 50;
  /** RegularExpression Id. */
  int LONG = 51;
  /** RegularExpression Id. */
  int NATIVE = 52;
  /** RegularExpression Id. */
  int NEW = 53;
  /** RegularExpression Id. */
  int NULL = 54;
  /** RegularExpression Id. */
  int PACKAGE = 55;
  /** RegularExpression Id. */
  int PRIVATE = 56;
  /** RegularExpression Id. */
  int PROTECTED = 57;
  /** RegularExpression Id. */
  int PUBLIC = 58;
  /** RegularExpression Id. */
  int RETURN = 59;
  /** RegularExpression Id. */
  int SHORT = 60;
  /** RegularExpression Id. */
  int STATIC = 61;
  /** RegularExpression Id. */
  int SUPER = 62;
  /** RegularExpression Id. */
  int SWITCH = 63;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 64;
  /** RegularExpression Id. */
  int THIS = 65;
  /** RegularExpression Id. */
  int THROW = 66;
  /** RegularExpression Id. */
  int THROWS = 67;
  /** RegularExpression Id. */
  int TRANSIENT = 68;
  /** RegularExpression Id. */
  int TRUE = 69;
  /** RegularExpression Id. */
  int TRY = 70;
  /** RegularExpression Id. */
  int VOID = 71;
  /** RegularExpression Id. */
  int VOLATILE = 72;
  /** RegularExpression Id. */
  int WHILE = 73;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 74;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 75;
  /** RegularExpression Id. */
  int HEX_LITERAL = 76;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 77;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 78;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 79;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 80;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 81;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 82;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 83;
  /** RegularExpression Id. */
  int STRING_LITERAL = 84;
  /** RegularExpression Id. */
  int LPAREN = 85;
  /** RegularExpression Id. */
  int RPAREN = 86;
  /** RegularExpression Id. */
  int LBRACE = 87;
  /** RegularExpression Id. */
  int RBRACE = 88;
  /** RegularExpression Id. */
  int LBRACKET = 89;
  /** RegularExpression Id. */
  int RBRACKET = 90;
  /** RegularExpression Id. */
  int SEMICOLON = 91;
  /** RegularExpression Id. */
  int COMMA = 92;
  /** RegularExpression Id. */
  int DOT = 93;
  /** RegularExpression Id. */
  int HASH = 94;
  /** RegularExpression Id. */
  int ASSIGN = 95;
  /** RegularExpression Id. */
  int LT = 96;
  /** RegularExpression Id. */
  int BANG = 97;
  /** RegularExpression Id. */
  int TILDE = 98;
  /** RegularExpression Id. */
  int HOOK = 99;
  /** RegularExpression Id. */
  int COLON = 100;
  /** RegularExpression Id. */
  int EQ = 101;
  /** RegularExpression Id. */
  int LE = 102;
  /** RegularExpression Id. */
  int GE = 103;
  /** RegularExpression Id. */
  int NE = 104;
  /** RegularExpression Id. */
  int SC_OR = 105;
  /** RegularExpression Id. */
  int SC_AND = 106;
  /** RegularExpression Id. */
  int INCR = 107;
  /** RegularExpression Id. */
  int DECR = 108;
  /** RegularExpression Id. */
  int PLUS = 109;
  /** RegularExpression Id. */
  int MINUS = 110;
  /** RegularExpression Id. */
  int STAR = 111;
  /** RegularExpression Id. */
  int SLASH = 112;
  /** RegularExpression Id. */
  int BIT_AND = 113;
  /** RegularExpression Id. */
  int BIT_OR = 114;
  /** RegularExpression Id. */
  int XOR = 115;
  /** RegularExpression Id. */
  int REM = 116;
  /** RegularExpression Id. */
  int PLUSASSIGN = 117;
  /** RegularExpression Id. */
  int MINUSASSIGN = 118;
  /** RegularExpression Id. */
  int STARASSIGN = 119;
  /** RegularExpression Id. */
  int SLASHASSIGN = 120;
  /** RegularExpression Id. */
  int ANDASSIGN = 121;
  /** RegularExpression Id. */
  int ORASSIGN = 122;
  /** RegularExpression Id. */
  int XORASSIGN = 123;
  /** RegularExpression Id. */
  int REMASSIGN = 124;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 125;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 126;
  /** RegularExpression Id. */
  int GT = 127;
  /** RegularExpression Id. */
  int IDENTIFIER = 137;
  /** RegularExpression Id. */
  int LETTER = 138;
  /** RegularExpression Id. */
  int PART_LETTER = 139;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"LOOKAHEAD\"",
    "\"IGNORE_CASE\"",
    "\"PARSER_BEGIN\"",
    "\"PARSER_END\"",
    "\"JAVACODE\"",
    "\"TOKEN\"",
    "\"SPECIAL_TOKEN\"",
    "\"MORE\"",
    "\"SKIP\"",
    "\"TOKEN_MGR_DECLS\"",
    "\"EOF\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 18>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 23>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"#\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"strictfp\"",
    "\"enum\"",
    "\"...\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"<<\"",
    "\"assert\"",
    "\"@\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
  };

}
