/* Generated By:JJTree: Do not edit this line. ASTIntConstNode.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTIntConstNode.h"
#include "SPLParserVisitor.h"

  
  ASTIntConstNode::ASTIntConstNode(int id) : SimpleNode(id) {
  }
  ASTIntConstNode::ASTIntConstNode(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTIntConstNode::~ASTIntConstNode() {
  }

  /** Accept the visitor. **/
  void ASTIntConstNode::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

