/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTVarDeclaration.h"
#include "SPLParserVisitor.h"

  
  ASTVarDeclaration::ASTVarDeclaration(int id) : SimpleNode(id) {
  }
  ASTVarDeclaration::ASTVarDeclaration(SPLParser *parser, int id) : SimpleNode(parser, id) {
  }
  ASTVarDeclaration::~ASTVarDeclaration() {
  }

  /** Accept the visitor. **/
  void ASTVarDeclaration::jjtAccept(SPLParserVisitor *visitor, void* data) const {
    visitor->visit(this, data);
  }

