/* Generated By:JJTree: Do not edit this line. ASTBNFLookahead.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFLookahead extends JJTreeNode{
  public ASTBNFLookahead(int id) {
    super(id);
  }

  public ASTBNFLookahead(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=23c1c72f5b505ecbcb07dd3d53e843ca (do not edit this line) */
