/* Generated By:JJTree: Do not edit this line. ASTREParenthesized.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREParenthesized extends JJTreeNode{
  public ASTREParenthesized(int id) {
    super(id);
  }

  public ASTREParenthesized(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cbce1328833ab2c2e8dbc6e02b986dbb (do not edit this line) */
