/* Generated By:JJTree: Do not edit this line. ASTREOneOrMore.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREOneOrMore extends JJTreeNode{
  public ASTREOneOrMore(int id) {
    super(id);
  }

  public ASTREOneOrMore(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b9a303fadaf9ed53390fd5049361f30 (do not edit this line) */
