/* Generated By:JJTree: Do not edit this line. ASTRESpec.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTRESpec extends JJTreeNode{
  public ASTRESpec(int id) {
    super(id);
  }

  public ASTRESpec(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=75381cced68823125a7e2260354fd0aa (do not edit this line) */
