/* Generated By:JJTree: Do not edit this line. ASTOptions.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTOptions extends JJTreeNode{
  public ASTOptions(int id) {
    super(id);
  }

  public ASTOptions(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bab47a15ec88dcb8fb44fea005cf17c9 (do not edit this line) */
