/* Generated By:JJTree: Do not edit this line. ASTBNFNonTerminal.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTBNFNonTerminal extends JJTreeNode {
  public ASTBNFNonTerminal(int id) {
    super(id);
  }

  public ASTBNFNonTerminal(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=73d1ee011d16502336c59821448c2b06 (do not edit this line) */
