/* Generated By:JJTree: Do not edit this line. ASTBNFChoice.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTBNFChoice extends JJTreeNode {
  public ASTBNFChoice(int id) {
    super(id);
  }

  public ASTBNFChoice(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ee18e2e8ee7e6e42249ba72434f77304 (do not edit this line) */
