/* Generated By:JJTree: Do not edit this line. ASTBNFZeroOrMore.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFZeroOrMore extends JJTreeNode{
  public ASTBNFZeroOrMore(int id) {
    super(id);
  }

  public ASTBNFZeroOrMore(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=546ee267d3fb68a46c1903eba27578f5 (do not edit this line) */
