/* Generated By:JJTree: Do not edit this line. ASTBNFTryBlock.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTBNFTryBlock extends JJTreeNode {
  public ASTBNFTryBlock(int id) {
    super(id);
  }

  public ASTBNFTryBlock(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4386e3b602be15bf2e5572963b67df89 (do not edit this line) */
