/* Generated By:JJTree: Do not edit this line. ASTBNFTryBlock.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFTryBlock extends JJTreeNode{
  public ASTBNFTryBlock(int id) {
    super(id);
  }

  public ASTBNFTryBlock(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d21ffab193632f97de92a8956dd20fdd (do not edit this line) */
