/* Generated By:JJTree: Do not edit this line. ASTBNFZeroOrOne.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTBNFZeroOrOne extends JJTreeNode {
  public ASTBNFZeroOrOne(int id) {
    super(id);
  }

  public ASTBNFZeroOrOne(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dc5e7f29cae1296583641c8a0a798741 (do not edit this line) */
