/* Generated By:JJTree: Do not edit this line. ASTBNFZeroOrMore.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTBNFZeroOrMore extends JJTreeNode {
  public ASTBNFZeroOrMore(int id) {
    super(id);
  }

  public ASTBNFZeroOrMore(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=91c60af592593f03df75ec6542516fcf (do not edit this line) */
