/* Generated By:JJTree: Do not edit this line. ASTBNFSequence.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTBNFSequence extends JJTreeNode {
  public ASTBNFSequence(int id) {
    super(id);
  }

  public ASTBNFSequence(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0f655f32f593bbfa25190c9e4dc5ac20 (do not edit this line) */
