/* Generated By:JJTree: Do not edit this line. ASTBNFLookahead.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTBNFLookahead extends JJTreeNode {
  public ASTBNFLookahead(int id) {
    super(id);
  }

  public ASTBNFLookahead(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0cf0425a10bb62172b2162fa60c4784a (do not edit this line) */
