/* Generated By:JJTree: Do not edit this line. ASTBNFParenthesized.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTBNFParenthesized extends JJTreeNode {
  public ASTBNFParenthesized(int id) {
    super(id);
  }

  public ASTBNFParenthesized(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6a087c9fb8e0e4844d99f6f856156c2e (do not edit this line) */
