/* Generated By:JJTree: Do not edit this line. ASTBNFOneOrMore.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTBNFOneOrMore extends JJTreeNode{
  public ASTBNFOneOrMore(int id) {
    super(id);
  }

  public ASTBNFOneOrMore(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7f86baee0698ad85aef0406a45085a17 (do not edit this line) */
