/* Generated By:JJTree: Do not edit this line. ASTCharDescriptor.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTCharDescriptor extends JJTreeNode{
  public ASTCharDescriptor(int id) {
    super(id);
  }

  public ASTCharDescriptor(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=caa87bfaa4c0977389440998ccd2bf59 (do not edit this line) */
