/* Generated By:JJTree: Do not edit this line. ASTCharDescriptor.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTCharDescriptor extends JJTreeNode {
  public ASTCharDescriptor(int id) {
    super(id);
  }

  public ASTCharDescriptor(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=19dbb61991f1b04572245baa1efea01e (do not edit this line) */
