/* Generated By:JJTree: Do not edit this line. ASTREOneOrMore.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREOneOrMore extends JJTreeNode{
  public ASTREOneOrMore(int id) {
    super(id);
  }

  public ASTREOneOrMore(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c3d37cb3446c7e5f2cc9243ba32db115 (do not edit this line) */
