/* Generated By:JJTree: Do not edit this line. ASTRRepetitionRange.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTRRepetitionRange extends JJTreeNode {
  public ASTRRepetitionRange(int id) {
    super(id);
  }

  public ASTRRepetitionRange(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=26e985a38676c09e030ea12b8d409841 (do not edit this line) */
