/* Generated By:JJTree: Do not edit this line. ASTREZeroOrOne.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREZeroOrOne extends JJTreeNode{
  public ASTREZeroOrOne(int id) {
    super(id);
  }

  public ASTREZeroOrOne(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7a82043bf29ef56f3304163eb8dbef57 (do not edit this line) */
