/* Generated By:JJTree: Do not edit this line. ASTRRepetitionRange.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTRRepetitionRange extends JJTreeNode{
  public ASTRRepetitionRange(int id) {
    super(id);
  }

  public ASTRRepetitionRange(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2781035a62114c91f0bbef62a272a717 (do not edit this line) */
