/* Generated By:JJTree: Do not edit this line. ASTREZeroOrMore.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTREZeroOrMore extends JJTreeNode {
  public ASTREZeroOrMore(int id) {
    super(id);
  }

  public ASTREZeroOrMore(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=983656f667464d500b345da1e454e9b3 (do not edit this line) */
