/* Generated By:JJTree: Do not edit this line. ASTREZeroOrMore.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREZeroOrMore extends JJTreeNode{
  public ASTREZeroOrMore(int id) {
    super(id);
  }

  public ASTREZeroOrMore(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fa3e9a267c8afbd0ba6696fdd9f03d32 (do not edit this line) */
