/* Generated By:JJTree: Do not edit this line. ASTREEOF.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREEOF extends JJTreeNode{
  public ASTREEOF(int id) {
    super(id);
  }

  public ASTREEOF(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7ab3d6030062519cb080b48d2fd819e8 (do not edit this line) */
