/* Generated By:JJTree: Do not edit this line. ASTRENamed.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTRENamed extends JJTreeNode {
  public ASTRENamed(int id) {
    super(id);
  }

  public ASTRENamed(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4849e3718037a79aedbe7aec0bec0cbb (do not edit this line) */
