/* Generated By:JJTree: Do not edit this line. ASTRE.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTRE extends JJTreeNode {
  public ASTRE(int id) {
    super(id);
  }

  public ASTRE(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=be69bbf2a1e41e33986477998a928c66 (do not edit this line) */
