/* Generated By:JJTree: Do not edit this line. ASTREZeroOrOne.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTREZeroOrOne extends JJTreeNode {
  public ASTREZeroOrOne(int id) {
    super(id);
  }

  public ASTREZeroOrOne(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0877edc1a5a47668e6cb21b7e28815ab (do not edit this line) */
