/* Generated By:JJTree: Do not edit this line. ASTREReference.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTREReference extends JJTreeNode{
  public ASTREReference(int id) {
    super(id);
  }

  public ASTREReference(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6b0035f242d2da5a694fbfc5afed4704 (do not edit this line) */
