/* Generated By:JJTree: Do not edit this line. ASTREParenthesized.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.javacc.jjtree;

public
class ASTREParenthesized extends JJTreeNode {
  public ASTREParenthesized(int id) {
    super(id);
  }

  public ASTREParenthesized(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c28161004a2a176f675bec97fd6fb465 (do not edit this line) */
