/* Generated By:JJTree: Do not edit this line. ASTTokenDecls.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.javacc.jjtree;

public class ASTTokenDecls extends JJTreeNode{
  public ASTTokenDecls(int id) {
    super(id);
  }

  public ASTTokenDecls(JJTreeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=37956bbc162702bf5bf5818fd9e20ebc (do not edit this line) */
